name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out repository code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

  discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Discord Webhook
        uses: johnnyhuy/actions-discord-git-webhook@v1.0.4
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
